"use client";
import { useEffect, useMemo, useState } from "react";
import { CircleMarker, MapContainer, Popup, TileLayer } from "react-leaflet";
import { api } from "../lib/api";
import { categories, type Category, type Report } from "../lib/types";
import { ReportList } from "./ReportList";
import styles from "./CommunityMap.module.css";
const colors:Record<Category,string>={"Unsafe Street":"#B83A3A","Poor Lighting":"#D07B20","Traffic Danger":"#7B4FA3","Harassment Concern":"#C5436F","Suspicious Activity":"#2F80A9","Other":"#627D98"};
export function CommunityMap(){const [reports,setReports]=useState<Report[]>([]),[category,setCategory]=useState(""),[start,setStart]=useState(""),[end,setEnd]=useState(""),[status,setStatus]=useState("approved"),[loading,setLoading]=useState(true),[error,setError]=useState("");useEffect(()=>{const q=new URLSearchParams();if(category)q.set("category",category);if(start)q.set("start_date",start);if(end)q.set("end_date",end);setLoading(true);api.reports(q.size?`?${q}`:"").then(setReports).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[category,start,end]);const mapped=useMemo(()=>reports.filter(x=>x.latitude!==null&&x.longitude!==null),[reports]);const unmapped=useMemo(()=>reports.filter(x=>x.latitude===null||x.longitude===null),[reports]);async function upvote(id:number){try{const updated=await api.upvote(id);setReports(items=>items.map(x=>x.id===id?updated:x))}catch(e){setError(e instanceof Error?e.message:"Could not record support.")}} return <><div className={styles.filters}><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>From<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>To<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><label>Report status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="approved">Approved (public)</option></select></label></div>{error&&<p className="notice">{error}</p>}{loading?<div className="card empty">Loading approved community reports…</div>:<><section className={styles.mapWrap} aria-label="Map of approved community safety reports"><MapContainer center={[30.3753,69.3451]} zoom={5} scrollWheelZoom={false}><TileLayer attribution="© OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>{mapped.map(r=><CircleMarker key={r.id} center={[r.latitude!,r.longitude!]} radius={10} pathOptions={{color:colors[r.category],fillColor:colors[r.category],fillOpacity:.8}}><Popup><strong>{r.category}</strong><h3>{r.title}</h3><p>{r.approximate_location_name}</p><p>{new Date(r.incident_at||r.created_at).toLocaleDateString()}</p><p>{r.description}</p><button className="button" onClick={()=>upvote(r.id)}>▲ {r.upvote_count} support</button></Popup></CircleMarker>)}</MapContainer></section><p className={styles.legend}>{categories.map(x=><span key={x}><i style={{background:colors[x]}}/>{x}</span>)}</p><section><h2>Reports without map pins</h2><p className="page-intro">These concerns are still useful context, but have no shared broad coordinates and are kept off the map.</p><ReportList reports={unmapped} onUpvote={upvote}/></section></>}</>}
